### ISSUE TITLE
Bot doesn't run

### ISSUE THREAD

**Issue by ACE-BOT-Boop** [kkrypt0nn/Python-Discord-Bot-Template#1]
Hello, I love your template and have followed all of the steps to making the bot but when I put in python3 bot.py into Command prompt it comes up with this, please help!
![Annotation 2020-05-29 092050](https://user-images.githubusercontent.com/65804540/83204000-0e907e80-a18e-11ea-92e6-d40c7dec17fc.png)

**Comment by chuckn408** [comment]
you need to install python3. you can get it here::
https://www.python.org/downloads/

**Comment by CyberDudeJ** [comment]
I am using a bot hosting service that has python 3. and still won't run

**Comment by CyberDudeJ** [comment]
nope works now i put it in the incorrect file

**Comment by macks2008** [comment]
Yeah, that error means it doesn't recognize/can't find the Python interpreter. Sometimes it's just a matter of putting it on the path, or typing the name of the interpreter's executable correctly. Same thing can happen if you don't have Java on the path and try to run a Java application from the command line.
(if you got it working, you should probably close this)

**Comment by kkrypt0nn** [comment]
Don't forget that if you have only Python 3 installed, just use `python bot.py`

**Comment by kkrypt0nn** [comment]
I will change the README.md file when I upload the version 2.0 of the template.
