### ISSUE TITLE
slash commands not working

### ISSUE THREAD

**Issue by stijnieboy150** [kkrypt0nn/Python-Discord-Bot-Template#101]
**Describe the bug**

**To Reproduce**

1. Given the following code ...
2. Using the following command '...'
3. Given the following arguments '...'

**Expected behavior**

**Screenshots**

**Template Version**
The version of the template that you are using.

**Additional context**

**Comment by kkrypt0nn** [comment]
Please read the FAQ first:

If slash commands are not showing up upon the first start of the bot this is perfectly normal behavior. You will need to <strong>synchronize</strong> them. You can easily do so by sending the following message in a channel your bot can read messages in
    <pre>@Bot sync <guild/global></pre>
    <i>Of course <code>@Bot</code> is you mentioning your actual bot.</i>
    <ul>
        <li>If you use <code>sync guild</code> the slash commands will only be available <strong>in the current guild</strong> where you've executed the command - this is perfect for testing your commands.</li>
        <li>If you use <code>sync global</code> the slash commands will be available in <strong>all guilds across all servers</strong> your bot is in - ideally you'd do that once you are sure the commands are working and you want to make them globally available.</li>
    </ul>

https://github.com/kkrypt0nn/Python-Discord-Bot-Template/wiki/Frequently-Asked-Questions#slash-commands-are-not-showing-up
