### ISSUE TITLE
command errors

### ISSUE THREAD

**Issue by mikarello** [kkrypt0nn/Python-Discord-Bot-Template#11]
the bot isn't responding to the commands and says they aren't to be found in the terminal, what should I do?

**Comment by kkrypt0nn** [comment]
Are you sure you're using correct commands? Have you edited something from the original code or not?
Any error logs that could help me to help you? If you wish a faster response you can always join my Discord server: https://discord.gg/HzJ3Gfr

**Comment by kkrypt0nn** [comment]
Issue forwarded on Discord.
