### ISSUE TITLE
The discord link doesn't work

### ISSUE THREAD

**Issue by coderoryx** [kkrypt0nn/Python-Discord-Bot-Template#13]
Hey, i wanted to join your discord but the link is invalid. I don't really know if it's my issue or your issue

**Comment by kkrypt0nn** [comment]
You might have cloned the previous repository. I've changed the link in the new versions:
https://discord.com/invite/HzJ3Gfr

**Comment by coderoryx** [comment]
yea sorry i found how to join it sorry for bothering ya

**Comment by kkrypt0nn** [comment]
No problem :)
