### ISSUE TITLE
intents module error

### ISSUE THREAD

**Issue by Lukegod2000** [kkrypt0nn/Python-Discord-Bot-Template#14]
getting this error 
in <module>
    intents = discord.Intents.default()
AttributeError: module 'discord' has no attribute 'Intents'

Any ideas how to fix it?

**Comment by kkrypt0nn** [comment]
Which version of discord.py are you using?
You can check in your code with:
`print(discord.__version__)`

**Comment by Lukegod2000** [comment]
> Which version of discord.py are you using?
> You can check in your code with:
> `print(discord.__version__)`

You are amazing I was running an old version I've updated it works like a dream now 

thank you!
