### ISSUE TITLE
Maybe add a cog template?

### ISSUE THREAD

**Issue by AstroOrbis** [kkrypt0nn/Python-Discord-Bot-Template#15]

**Comment by kkrypt0nn** [comment]
Is it really that hard?
Take a look at the [help cog](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/blob/master/cogs/help.py).

**Comment by AstroOrbis** [comment]
I just think that it would be easier... I’ll get to work on a command adder cog because _why the hell not_

**Comment by kkrypt0nn** [comment]
Will add in the new version, in a few minutes.

**Comment by kkrypt0nn** [comment]
Added in [version 2.3](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/releases/tag/2.3).

Next time don't hesitate to ask these type of things in my [discord server](https://discord.gg/HzJ3Gfr) as this is not really an "issue".
