### ISSUE TITLE
Would it be possible to recursively load cogs inside the “cogs” folder instead of adding them all into config.py?

### ISSUE THREAD

**Issue by AstroOrbis** [kkrypt0nn/Python-Discord-Bot-Template#16]
(At this point I’m just suggesting features lmao)

**Comment by kkrypt0nn** [comment]
It would be definitely possible, will eventually do that. Just that if people want not to load all cogs it's not really the best for them.

If you have any other suggestions I really appreciate them but it would be betyer if you tell them in the discord server :)

**Comment by AstroOrbis** [comment]
Rn the iPad I’m on doesn’t support discord for some reason (_death stares the school sysadmins_), so can I put them as separate issues until i get home?
