### ISSUE TITLE
Make a CREATOR tag in config.py, and make it unbannable

### ISSUE THREAD

**Issue by AstroOrbis** [kkrypt0nn/Python-Discord-Bot-Template#17]
Also for the owner tag

**Comment by AstroOrbis** [comment]
And unkickable and unwarnable

**Comment by AstroOrbis** [comment]
With a message that basically says screw you, you cant ban me

**Comment by AstroOrbis** [comment]
Lmao

**Comment by kkrypt0nn** [comment]
This is something you should implement in **your** personal bot, not to be added in a template.
