### ISSUE TITLE
Serverinfo command not working

### ISSUE THREAD

**Issue by coolguy21312** [kkrypt0nn/Python-Discord-Bot-Template#20]
server info command does not work i get this error every time i run it AttributeError: 'NoneType' object has no attribute 'id'


**Comment by Nyvil** [comment]
Hi! 
Reading this helps :)
https://github.com/kkrypt0nn/Python-Discord-Bot-Template#how-to-setup

**Comment by kkrypt0nn** [comment]
Fixed in the latest version, see [this](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/releases/tag/2.4.3).
