### ISSUE TITLE
[enh] Start supporting slash command

### ISSUE THREAD

**Issue by Aeris1One** [kkrypt0nn/Python-Discord-Bot-Template#21]
Slash Commands are actually in open beta phase but will soon™ become stable, they're supported by discord.py as an official addon (discord-py-slash-commands). 

It would be great for this template to support those commands, maybe on a separate branch because not all people wants to use them because of the beta-buggy status of those ones at the moment.

**Comment by kkrypt0nn** [comment]
Slash commands are in beta, this template is based on discord.py only, therefore I will implement the slash commands whenever they will be implemented in the discord.py library.
