### ISSUE TITLE
This is not an issue 

### ISSUE THREAD

**Issue by coolguy21312** [kkrypt0nn/Python-Discord-Bot-Template#23]
is there any way where you can make it where if a command is not found then the bot sends Command (What they tried to run) not found

**Comment by kkrypt0nn** [comment]
Yes you can, only problems are:
- if you want to add your bot in a bot list he will be denied because of that
- the bot can spam the chat with these error messages quite easily

**Comment by coolguy21312** [comment]
Ohhhh ok
