### ISSUE TITLE
Make it where there is a timeout on commands 

### ISSUE THREAD

**Issue by coolguy21312** [kkrypt0nn/Python-Discord-Bot-Template#24]
If you can please make it where there is a timeout on the commands so if someone spams a command the bot does not get rate   limited

**Comment by zedvais** [comment]
There is already this feature existed on the library. Just google it and implement it on your own.

**Comment by kkrypt0nn** [comment]
I will make one or two commands that has an implemented cooldown.
It's not a big deal, I will mention the version of the template here when it has been implemented.

**Comment by kkrypt0nn** [comment]
I make these issues on stream, so no thanks I can do it :D

**Comment by kkrypt0nn** [comment]
Added in version [2.6](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/releases/tag/2.6), see the [`dailyfact`](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/blob/2.6/cogs/fun.py#L36) command.
