### ISSUE TITLE
Replace bot.remove (...) with bot = ...(... , help_command=None

### ISSUE THREAD

**Issue by SimsumMC** [kkrypt0nn/Python-Discord-Bot-Template#40]
I'm on Mobile, so it's difficult for me. But in the main.py there is a not so beautiful thing. You don't need to use this weird bot.remove_command("help") instead just write in the bot definition the parameter help_command = None 🙃

**Comment by Nyvil** [comment]
Hi!

Thanks for your pull request. 

As you know, this is a template - everyone can edit the code as they want on their local machine. Personally, I don't believe that this is needed, as the remove call works just fine. But feel free to edit it in your local project:) 

Yet again,  thanks for your contribution
- Nyvil

**Comment by tooruu** [comment]
Where did you buy stars for this project? The code is indeed not so good. `bot.remove_command("help")` is discouraged even by discord.py itself and its forks.

**Comment by kkrypt0nn** [comment]
Small update for this one, it was something I had planned but always forgot - just like using a bot variable to access the config in other files.
Has been changed in a small code cleanup update.
