### ISSUE TITLE
Event to handle cuss words

### ISSUE THREAD

**Issue by HighnessAtharva** [kkrypt0nn/Python-Discord-Bot-Template#41]
I have a code snippet that automatically deletes messages with cuss words, tags the person and responds with the message 'Your message has not passed moderation'. Please respond if you'd like this feature to be implemented in the `bot.py` file in root directory.

**Comment by Nyvil** [comment]
Hi!

Thanks for your contribution, however this is a template and hence does not implement features  on request; it's meant to make life easier for people who want to start their bot, not us creating the bot for them.

Thank you once again,
Nyvil

//close
