### ISSUE TITLE
slash commands

### ISSUE THREAD

**Issue by yawn999** [kkrypt0nn/Python-Discord-Bot-Template#47]
went does ``@cog_ext.cog_slash(
    name="command",
    description="Command description",
    guild_ids=[GUILD_ID1, GUILD_ID2]
)``
go?

**Comment by kkrypt0nn** [comment]
There are default commands where you can see it, see the [`ping`](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/blob/master/cogs/general.py#L130) command for example.

**Comment by yawn999** [comment]
so I do not have to enable anything, just invite the bot with applications.commands?

**Comment by kkrypt0nn** [comment]
Please read [this file](https://github.com/kkrypt0nn/Python-Discord-Bot-Template/blob/master/README.md) in it's entirety.
