### ISSUE TITLE
SyncWarning: Failed to overwrite global commands

### ISSUE THREAD

**Issue by MarioProjects** [kkrypt0nn/Python-Discord-Bot-Template#51]
Hello, first of all thanks for the template! It works and is very easy to understand. My bot is working and running and responding to my custom commands but I dont know why I get that sometimes.

> python bot.py 
```

Loaded extension 'general-slash'
/home/maparla/anaconda3/envs/cenv/lib/python3.10/site-packages/disnake/ext/commands/interaction_bot_base.py:715: SyncWarning: Failed to overwrite global commands due to 400 Bad Request (error code: 50035): Invalid Form Body
In 0.options.2.name: String value did not match validation regex.
  warnings.warn(f"Failed to overwrite global commands due to {e}", SyncWarning)
Logged in as ChickHelp
disnake API version: 2.3.0
Python version: 3.10.0
Running on: Linux 5.11.0-46-generic (posix)
```

**Comment by kkrypt0nn** [comment]
Hey,

The option name on a command is not a valid string. According to the Discord API documentation option names are defined as the following:
> `CHAT_INPUT` command names and command option names must match the following regex `^[\w-]{1,32}$` with the unicode flag set. If there is a lowercase variant of any letters used, you must use those. Characters with no lowercase variants and/or uncased letters are still allowed. `USER` and `MESSAGE` commands may be mixed case and can include spaces.

So make sure you name your option names correctly.

**Comment by MarioProjects** [comment]
Yes, was that thanks a lot @kkrypt0nn 

I have another question, not regarding this warning. I want to do a choices param so I included the choices argument on Option. When I call the command I don't see the options as I see on other bots, and also don't see any example using that behavior... Do you know how to accomplish it? 

```
Option(
    name="collection",
    description=f"Available collections: {', '.join(COLLECTION_PROFITS.keys())}.",
    type=OptionType.string,
    choices=["Chickenz", "TheChickenz", "TheChickenz Unique", "PixelChickenz"],
    required=True
)
```

**Comment by kkrypt0nn** [comment]
Thanks for pointing that out, I will make a command using choices arguments in the next update.

For me it looks good, you got any errors? I used something very similar for my bot on my Discord server and I get the following output:
![image](https://user-images.githubusercontent.com/43011723/149928601-99ee6431-c929-4fd7-8a77-0bd2942e85e2.png)

**Comment by MarioProjects** [comment]
Okey, now I am displaying the options... Maybe needs around 30 minutes to fully update the bot? I am testing and doing continuous changes. Could be that?

**Comment by kkrypt0nn** [comment]
That can be something yes, I would use the `guild_ids` attribute in the command decorator when testing commands as explained [here](https://github.com/kkrypt0nn/Python-Discord-Bot-Template#disclaimer).

**Comment by MarioProjects** [comment]
Okey thank you so much. So using `guild_ids = [discord_id]` as for `OWNERS`, would work instantaneously, just for me or for all people?, should I remove that after testing or I can put it there for always without problems? 

Thanks again :)
