### ISSUE TITLE
Can't install disnake

### ISSUE THREAD

**Issue by BlueDragonGXX** [kkrypt0nn/Python-Discord-Bot-Template#54]
I have been trying to do pip install disnake but it only shows this:
**C:\Users\blued\Documents\GitHub\DiscordBotTest>pip install disnake
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Could not find a version that satisfies the requirement disnake (from versions: none)
ERROR: No matching distribution found for disnake**

If anyone knows what is happening please help me

**Comment by kkrypt0nn** [comment]
The error pretty much says all: You're using an old script wrapper.
So either take a look at the issue N°5599 of pip or use `python -m pip install ...`.
