### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ACE-BOT-Boop** [kkrypt0nn/Python-Discord-Bot-Template#6]
I edited everything in the script and went to command prompt put in the command and I hit enter and nothing happend, what do I do?
![Annotation 2020-09-09 190711](https://user-images.githubusercontent.com/65804540/92578811-b9f1b900-f2cf-11ea-8bf7-deeeac3e443f.png)

**Comment by kkrypt0nn** [comment]
Please join the discord server, other people can also help you: https://discord.gg/HzJ3Gfr
