### ISSUE TITLE
Move database from json to sql

### ISSUE THREAD

**Issue by CaedenPH** [kkrypt0nn/Python-Discord-Bot-Template#60]
As the title says, move the example *from* json to an sql-like database, such as `sqlite`. This imposes the challenge of the user having to set up a database, which is good experience for the user and teaches them not to use storage types such as json.  

https://github.com/kkrypt0nn/Python-Discord-Bot-Template/pull/59

**Comment by kkrypt0nn** [comment]
That is in my Todo list, yeah, but I believe they way you've implemented in the PR was a "as quickly as possible" made feature for it and doesn't contain what it should. For me the PR is a poor implementation of sqlite.

My plans were to move to sqlite once I move it back to discord.py 2.0 (stable, not beta). Hence I don't plan on implementing before doing so.
If discord.py doesn't make a stable release in the coming month, I will move in the coming month.
