### ISSUE TITLE
sqlite3 downloading error

### ISSUE THREAD

**Issue by DemonChrisey** [kkrypt0nn/Python-Discord-Bot-Template#66]
Hello There!
I am opening this issue with regards to the 'requirements.txt' file as it cannot download sqlite3 stating the following error

**ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3**

Running On Latest Python & PIP Version
I am wondering if this is an error of PIP or of the requirements.txt file

**Comment by kkrypt0nn** [comment]
Feel free to remove it from the requirements.txt file, it's already installed by default when installing Python.
