### ISSUE TITLE
load_cogs not awaited

### ISSUE THREAD

**Issue by OhhTuRnz** [kkrypt0nn/Python-Discord-Bot-Template#73]
When some cog isn't loaded, it generates an asyncio runtime error because it was not awaited.

**Comment by shndowbots** [comment]
Does this happen when you try running a command in the unloaded cog?

**Comment by kkrypt0nn** [comment]
To help, we'd need the traceback as you gave no information for us to help you.

**Comment by kkrypt0nn** [comment]
Reason for 'edited code' label is that it works fine when using the raw unedited template:
![Screenshot 2022-10-12 090515](https://user-images.githubusercontent.com/43011723/195273671-44c0817c-3d3a-4987-9480-8bbe58934d8d.png)

Commands executed:
```
--help
--unload template
--testcommand (Cog was unloaded, hence the error)
--help
```

**Comment by OhhTuRnz** [comment]
Sorry to not answer, had a bit of problems and was off quite alot. That error happened to me when the cog that was trying to load failed, and the app tried to load another cog giving that error. The app worked fine but it was just a debug error that looked a bit bad.
