### ISSUE TITLE
ModuleNotFoundError: No module named 'aiosqlite'

### ISSUE THREAD

**Issue by ProjectEdotAI** [kkrypt0nn/Python-Discord-Bot-Template#86]
Yes, I installed it by:
`python -m pip install -r requirements.txt`
yet it is still not being imported, I uninstall and reinstall it, but it still didn't work.
Is this a high-skill issue?
Please help.

**Comment by ProjectEdotAI** [comment]
(I also restarted by pc)

**Comment by kkrypt0nn** [comment]
If you start the bot with something like `python3 bot.py` then you should install with `python3 -m pip install -r requirements.txt`

**Comment by ProjectEdotAI** [comment]
> If you start the bot with something like `python3 bot.py` then you should install with `python3 -m pip install -r requirements.txt`

It still did not detect aiosqlite, but It ran but having:
`
[2023-05-23 21:27:59] [ERROR   ] discord_bot: Failed to load extension moderation
ExtensionFailed: Extension 'cogs.moderation' raised an error: ImportError: cannot import name 'app_commands' from 'discord' (C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\__init__.py)
[2023-05-23 21:27:59] [ERROR   ] discord_bot: Failed to load extension template
ExtensionFailed: Extension 'cogs.template' raised an error: AttributeError: module 'discord.ext.commands' has no attribute 'hybrid_command'
`

**Comment by kkrypt0nn** [comment]
That means you have discord.py < 2.0 installed. You can upgrade with `python(3) -m pip install discord.py -U`

**Comment by ProjectEdotAI** [comment]
> That means you have discord.py < 2.0 installed. You can upgrade with `python(3) -m pip install discord.py -U`

Thanks
