### ISSUE TITLE
No commands

### ISSUE THREAD

**Issue by J45onDev** [kkrypt0nn/Python-Discord-Bot-Template#88]
I can't run any commands with the prefix and /. Then / commands doesn't even show up.

**Comment by kkrypt0nn** [comment]
If slash commands are not showing up upon the first start of the bot this is perfectly normal behavior. You will need to **synchronize** them. You can easily do so by sending the following message in the chat
```
@Bot sync <guild/global>
```
*Of course `@Bot` is you mentioning your actual bot.*

• If you use `sync guild` the slash commands will only be available **in the current guild** where you've executed the command - this is perfect for testing your commands.
• If you use `sync global` the slash commands will be available in **all guilds across all servers** your bot is in - ideally you'd do that once you are sure the commands are working and you want to make them globally available.
