### ISSUE TITLE
doubled commands

### ISSUE THREAD

**Issue by olususus** [kkrypt0nn/Python-Discord-Bot-Template#92]
i have changed the command description, and now they are doubled. how can i remove them?

**Comment by kkrypt0nn** [comment]
Hey,

If you see twice the same slash command for the bot this means that you have both **global** and **guild** commands. You will need to `unsync` them from either the global scope or the guild scope - this can be done with
```
@Bot unsync <guild/global>
```
*Of course `@Bot` is you mentioning your actual bot.*

**Comment by olususus** [comment]
thanks
